### ISSUE TITLE
Remove duplicate users

### ISSUE THREAD

**Issue by angaither** [DoSomething/northstar#187] opened 2015-07-27 20:46 UTC
Refs #182 

Need to go into production and write a script that searches all users, looks to see if there is another user with that email/mobile
then removes the user with the most recent `updated_at` attribute (as that is the second time the user was added from the script) 

This should be a [custom artisan command](http://laravel.com/docs/5.1/artisan#writing-commands) that first grabs all users, loops through each one, and searches for a user with the same email or phone number.

**Comment by chloealee** [comment] 2015-08-03 17:23
@angaither It looks like mobile numbers are getting stored in various formats in the DB (some stored as 6179093032 vs. 617-909-3032 vs. 236.993.4015x563 etc). Do you think it's a better idea to convert them in this script or overall when they get saved, similar to how email addresses are stored all to lowercase right when it is created?

**Comment by angaither** [comment] 2015-08-05 13:59
@chloealee we should probably sanitize them before they are saved, I would say we could save them just as numbers, no dashes, parenthesis or letters. I know when we seed with faker we get those extensions, but we shouldn't actually have any extensions in real data. 

cc @jonuy

**Comment by chloealee** [comment] 2015-08-05 14:10
@angaither makes sense! So should this should happen in the `User` model, not in the script?

**Comment by angaither** [comment] 2015-08-05 14:24
correct!

**Comment by angaither** [comment] 2015-08-05 14:24
But if we have users with funky formatted phone numbers already, we might also have to address fixing it in a script

**Comment by chloealee** [comment] 2015-08-05 14:30
@angaither okay great! I will add that to the `User` model now. 

Should the phone number conversion be in a separate script? If so, I can create an issue for that and assign it to myself!

**Comment by chloealee** [comment] 2015-08-05 17:29
Also, I chatted with @DFurnes  a little about the script yesterday to make sure that my logic made sense and I was on the right track. He said that the logic in my foreach loop seemed to make sense however, it would take forever to loop through all the users in our database. Instead, he suggested using an eloquent query to find the duplicates and then deleting the most recently `updated_at` from that result set. I’ve been trying various ways to query for duplicates, expecting to get an array of those records that have the email twice, but keep getting 57 records when it should only be 4… here is the code I think is closest to what we want `$duplicates = User::groupBy('email')->havingRaw('count(*) > 1')->get();` but I think this might be counting how many emails the user has instead of how many times the email it occurs? Do you know anything that comes out of the box to search for occurrences?

**Comment by chloealee** [comment] 2015-08-05 22:01
@angaither I got the script to work (right now just for emails, but if this is the correct route, will add in same logic for mobile numbers)! However there are quite a few `foreach` blocks so I'm still not sure if this is the most efficient way to remove duplicate users. I just created a PR for you to see the route I'm going down to see if it's okay and if I should keep going this way - whenever you get a chance please let me know!

**Comment by angaither** [comment] 2015-08-06 14:56
@chloealee you could do a nested query with sql, I'm not sure eloquent will have an out of the box solution for that, and I don't know if it's supported with mongo. 
But you can do a DB:select('with whatever statement inside') for eloquent sql queries. 

http://stackoverflow.com/questions/4224773/fast-way-to-find-duplicates-on-indexed-column-in-mongodb

I don't know much about mongo aggregation, and yeah, this for loop route will take forever, but I just don't have the mongo query foo to know how to write this the correct way.

**Comment by chloealee** [comment] 2015-08-06 18:45
got it, thanks @angaither !

**Comment by angaither** [comment] 2015-08-17 18:39
query: 
```
db.getCollection('users').aggregate([   
   { $group: {      
       _id: { email: "$email"},     
      uniqueIds: { $addToSet: "$_id" },     
      count: { $sum: 1 }    
   }},    
   { $match: {     
     count: { $gt: 1 }    
   }} 
])
```

errors: 
```
assert: command failed: {
	"ok" : 0,
	"errmsg" : "not authorized on admin to execute command { aggregate: \"users\", pipeline: [ { $group: { _id: { email: \"$email\" }, uniqueIds: { $addToSet: \"$_id\" }, count: { $sum: 1.0 } } }, { $match: { count: { $gt: 1.0 } } } ], cursor: {} }",
	"code" : 13
} : aggregate failed
Error: command failed: {
	"ok" : 0,
	"errmsg" : "not authorized on admin to execute command { aggregate: \"users\", pipeline: [ { $group: { _id: { email: \"$email\" }, uniqueIds: { $addToSet: \"$_id\" }, count: { $sum: 1.0 } } }, { $match: { count: { $gt: 1.0 } } } ], cursor: {} }",
	"code" : 13
} : aggregate failed
    at Error (<anonymous>)
    at doassert (src/mongo/shell/assert.js:11:14)
    at Function.assert.commandWorked (src/mongo/shell/assert.js:254:5)
    at DBCollection.aggregate (src/mongo/shell/collection.js:1278:12)
    at (shell):1:27
2015-08-17T18:41:21.192+0000 E QUERY    Error: command failed: {
	"ok" : 0,
	"errmsg" : "not authorized on admin to execute command { aggregate: \"users\", pipeline: [ { $group: { _id: { email: \"$email\" }, uniqueIds: { $addToSet: \"$_id\" }, count: { $sum: 1.0 } } }, { $match: { count: { $gt: 1.0 } } } ], cursor: {} }",
	"code" : 13
} : aggregate failed
    at Error (<anonymous>)
    at doassert (src/mongo/shell/assert.js:11:14)
    at Function.assert.commandWorked (src/mongo/shell/assert.js:254:5)
    at DBCollection.aggregate (src/mongo/shell/collection.js:1278:12)
    at (shell):1:27 at src/mongo/shell/assert.js:13

```

@sheydari-ds can you help @chloealee run this on prod to determine how many duplicate users we have/what the differences are between the users.

**Comment by sheydari-ds** [comment] 2015-08-17 18:48
@angaither Will do. I'll touch base with her later today.

**Comment by sheydari-ds** [comment] 2015-08-18 21:15
@angaither @chloealee New error message when ran as superuser:

```
assert: command failed: {
        "errmsg" : "exception: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.",
        "code" : 16945,
        "ok" : 0
} : aggregate failed
Error: command failed: {
        "errmsg" : "exception: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.",
        "code" : 16945,
        "ok" : 0
} : aggregate failed
    at Error (<anonymous>)
    at doassert (src/mongo/shell/assert.js:11:14)
    at Function.assert.commandWorked (src/mongo/shell/assert.js:254:5)
    at DBCollection.aggregate (src/mongo/shell/collection.js:1278:12)
    at (shell):1:27
2015-08-18T21:18:09.217+0000 E QUERY    Error: command failed: {
        "errmsg" : "exception: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.",
        "code" : 16945,
        "ok" : 0
} : aggregate failed
    at Error (<anonymous>)
    at doassert (src/mongo/shell/assert.js:11:14)
    at Function.assert.commandWorked (src/mongo/shell/assert.js:254:5)
    at DBCollection.aggregate (src/mongo/shell/collection.js:1278:12)
    at (shell):1:27 at src/mongo/shell/assert.js:13
```

Looks like this might address issue, and there's not enough RAM to support the query:

http://stackoverflow.com/questions/26069601/how-to-aggregate-on-huge-array-in-mongodb

**Comment by chloealee** [comment] 2015-08-19 13:49
great, thanks @sheydari-ds ! I'll check out that stackoverflow and try to clean up the query.

**Comment by chloealee** [comment] 2015-08-19 14:39
@sheydari-ds will this work?

```
db.getCollection('users').aggregate([
  { $group: { 
     _id: { email: "$email"},
    uniqueIds: { $addToSet: "$_id" },
    count: { $sum: 1 } 
  }}, 
  { $match: { 
    count: { $gt: 1 } 
  }},
//   { $out:"result" }
], {
    allowDiskUse:true,
    cursor:{}
}
);

// db.result.find();
``` 

Followed the stackoverflow exactly but I think we can comment out those lines I did and should still work.

**Comment by sheydari-ds** [comment] 2015-08-20 19:55
Confirmed working @chloealee! But with Super user permissions. We have to figure out auth to run that properly as app. I'll look into required perms.

cc @angaither

**Comment by chloealee** [comment] 2015-08-20 19:56
Great, thank you @sheydari-ds !

**Comment by sheydari-ds** [comment] 2015-08-21 16:50
Looks like the perms are working now! @chloealee Can you double check on your side and confirm?

**Comment by chloealee** [comment] 2015-08-21 17:15
@sheydari-ds thanks for this! Now running into another problem - it looks like MongoDB based Eloquent model and query builder library we're using doesn't support `allowDiskUse` right now - I'm researching if we can easily add it on our own to support or if we'll have to resort to another solution.

**Comment by sheydari-ds** [comment] 2015-08-21 17:43
Oi. :/

**Comment by chloealee** [comment] 2015-08-24 14:32
I did some research about alternatives to `allowDiskUse` and couldn't find anything. Chatted with Uy and he suggested another route to take besides my initial query before using `allowDiskUse`/mongo query with all the `for loops` - pseudo code below. 

```
 $users = Users::all();

$users_alphabetical_order = $users->sortBy('email');

for(i = 0, i < users.length, i++) {
  user[i]->email
  if (user[i]->email == users[i + 1]->email) {
    // this is a duplicate
    // combine duplicate fields and delete all records but first created 
    i --;
  } else {
    // continue 
  }
}
```

**Comment by angaither** [comment] 2015-08-24 14:51
@chloealee this looks good, the only :question: I have is what if there's more than one with the same email

**Comment by chloealee** [comment] 2015-08-24 14:59
@angaither since all the duplicates will be next to each other (since they're sorted alphabetically) it should always find any duplicates in the if statement when it loops through. If it finds one, then it'll combine the appropriate fields to one record and delete. Then the `i --;` will set it back a record to compare to the next and continue. I think that should account for more then one with the same email. 

Also - do you think I should add a placeholder for where it left off in case the script times out and we need to run it again (similar to how you did this in your script to transfer user data)?

**Comment by angaither** [comment] 2015-08-24 18:30
yeah, you should def set something on the user, or a variable in cache to save where the script leaves off if it times out :+1:

**Comment by chloealee** [comment] 2015-08-24 18:54
okay great, thanks Andrea!

**Closed** 2015-12-16 14:51 UTC
Labels: bug
