### ISSUE TITLE
Submitting a user register when the user already exists will overwrite existing data

### ISSUE THREAD

**Issue by jonuy** [DoSomething/northstar#172] opened 2015-07-14 15:42 UTC
This means it can be used maliciously to allow one person to change another's password and have access to their account.

ref: https://github.com/DoSomething/LetsDoThis-iOS/issues/126

**Comment by aaronschachter** [comment] 2015-07-21 15:56
@jonuy has there been a recent change to close this issue? I'm now getting an error back when I use the same email to register in the iOS app... but definitely wasn't when i opened https://github.com/DoSomething/LetsDoThis-iOS/issues/126

**Comment by jonuy** [comment] 2015-07-21 16:26
Hm, not that I can recall. ¯\\_(ツ)_/¯

What error do you get back?

**Comment by aaronschachter** [comment] 2015-07-21 17:17
Nevermind, confirmed this is still a bug, I can can regularly register with `john.connor@dosomething.org` and keep overwriting the passwords.  The error I was getting back seems to other emails I was testing with.

Ideally we need this resolved to fully test the Login Registration flow, as we'd need some sort of message to indicate that an account for the email already exists in https://github.com/DoSomething/LetsDoThis-iOS/issues/19

**Comment by aaronschachter** [comment] 2015-07-21 19:25
@jonuy We will run into this issue with mobile number as well. Ideally should get a response back indicating the mobile number is already in use with an account.

**Comment by aaronschachter** [comment] 2015-07-23 18:27
My mistake, we don't run into this issue with mobile number because we do check for it: #183. That's what happens when you assume..

**Comment by aaronschachter** [comment] 2015-07-23 18:44
Note that this check should be case insensitive (#184)

**Comment by chloealee** [comment] 2015-07-29 14:51
@jonuy @aaronschachter Question - should we create a new `create` function breaking the logic out into creating a new user - if the user exists, throw an error message (#183). If not, create the user. Or throw login into the if block from lines 41-45?

**Comment by jonuy** [comment] 2015-08-03 15:20
There's already login logic that happens later on in the UserController::store function. If a user exists, we basically shouldn't allow the password setting to be overwritten. If a password is provided, I think it's safe to error out then. Otherwise, if the password matches, then continue on.

**Comment by chloealee** [comment] 2015-08-06 16:40
@jonuy ah got it, I think I was overcomplicating this in my head and also looking to add int he wrong place. This edit will happen in the `login` function in the `AuthController`, right? For some reason I wanted to add this login in the `store` function in the `UserController`

**Comment by chloealee** [comment] 2015-08-06 17:28
got it, thanks @jonuy ! I think I again was overthinking this.

**Closed** 2015-08-07 14:42 UTC

**Comment by aaronschachter** [comment] 2015-08-07 15:55
@chloealee Please let me know when this is deployed, so I can make sure to test/close out https://github.com/DoSomething/LetsDoThis-iOS/issues/126
